@startuml dbschema
enum Status {
    active
    inactive
    deleted
}

class User {
    user_id : uuid
    given_name : string
    family_name: string
    username : string
    email : string
    phone : string
    date_of_birth : string
    gender : string
    status : Status
    primary : boolean
    alternate_email : string
    alternate_phone : string
    deleted_at : timestamp
    avatar : string
    myOrganizationOrganizationId : uuid
    created_at : timestamp
    updated_at : timestamp
}

class Class {
    class_id : uuid
    class_name : string
    organizationOrganizationId : uuid
    shortcode : string
    status : status
    deleted_at : timestamp
    created_at : timestamp
    updated_at : timestamp
    academic_term_id : uuid
}

class ClassAgeRangesAgeRange {
    classClassId : uuid
    ageRangeId : uuid
}

class ClassGradesGrade {
    classClassId : uuid
    gradeId : uuid
}

class ClassSubjectsSubject {
    classClassId : uuid
    subjectId : uuid
}

class ClassProgramsProgram {
    classClassId : uuid
    programId : uuid
}

class Organization {
    organization_id : uuid
    organization_name : string
    address1 : string
    address2 : string
    phone : string
    shortCode : string
    status : status
    primaryContactUserId : uuid
    deleted_at : timestamp
    created_at : timestamp
    updated_at : timestamp
}

class OrganizationMembership {
    user_id : string
    organization_id : string
    join_timestamp : timestamp
    shortcode : string
    status : Status
    deleted_at : timestamp
    status_updated_at : timestamp
    userUserId : uuid
    organizationOrganizationId : uuid
    created_at : timestamp
    updated_at : timestamp
}

class Permission {
    role_id : uuid
    permission_id : string
    permission_name : string
    permission_category : string
    permission_group : string
    permission_level : string
    allow : boolean
    permission_description : string
    created_at : timestamp
    updated_at : timestamp
    status : Status
}

class Role {
    role_id : uuid
    role_name : string
    role_description : string
    status : status
    system_role : bool
    deleted_at : timestamp
    organizationOrganizationId : uuid
    created_at : timestamp
    updated_at : timestamp
}

class School {
    school_id : uuid
    school_name : string
    shortcode : string
    status : status
    organizationOrganizationId : uuid
    deleted_at : timestamp
    created_at : timestamp
    updated_at : timestamp
}

class SchoolProgramsProgram {
    schoolSchoolId : uuid
    programId : uuid
}

class SchoolMembership {
    user_id : string
    school_id : string
    join_timestamp : timestamp
    deleted_at : timestamp
    status_updated_at : timestamp
    status : Status
    userUserId : uuid
    schoolSchoolId : uuid
    created_at : timestamp
    updated_at : timestamp
}

class RoleMembershipsOrganizationMembership {
    roleRoleId : uuid
    organizationMembershipUserId : string
    organizationMembershipOrganizationId : string
}

class RoleSchoolMembershipsSchoolMembership {
    roleRoleId : uuid
    schoolMembershipUserId : string
    schoolMembershipSchoolId : string
}

class UserClassesStudyingcClass {
    userUserId : uuid
    classClassId : uuid
}

class UserClassesTeachingClass {
    userUserId : uuid
    classClassId : uuid
}

class SchoolClassesClass {
    schoolSchoolId : uuid
    classClassId : uuid
}

enum AgeRangeUnit {
    month
    year
}

class AgeRange {
    id : uuid
    name : string
    high_value : integer
    low_value : integer
    high_value_unit : AgeRangeUnit
    low_value_unit : AgeRangeUnit
    system : boolean
    status : Status
    created_at : timestamp
    deleted_at : timestamp
    organization_id : uuid
    updated_at : timestamp
}

class Subcategory {
    id : uuid
    name : string
    system : boolean
    status : Status
    created_at : timestamp
    deleted_at : timestamp
    organization_id : uuid
    updated_at : timestamp
}

class Grade {
    id : uuid
    name : string
    system : boolean
    status : Status
    created_at : timestamp
    progress_from_grade_id : uuid
    progress_to_grade_id : uuid
    deleted_at : timestamp
    organization_id : uuid
    updated_at : timestamp
}

class Category {
    id : uuid
    name : string
    system : boolean
    status : Status
    created_at : timestamp
    deleted_at : timestamp
    organization_id : uuid
    updated_at : timestamp
}

class CategorySubcategoriesSubcategory {
    categoryId : uuid
    subcategoryId : uuid
}

class Subject {
    id : uuid
    name : string
    system : boolean
    status : Status
    created_at : timestamp
    deleted_at : timestamp
    organization_id : uuid
    updated_at : timestamp
}

class SubjectCategoriesCategory {
    subjectId : uuid
    categoryId : uuid
}

class Program {
    id : uuid
    name : string
    system : boolean
    status : Status
    created_at : timestamp
    deleted_at : timestamp
    organization_id : uuid
    updated_at : timestamp
}

class ProgramAgeRangesAgeRange {
    programId : uuid
    ageRangeId : uuid
}

class ProgramGradesGrade {
    programId : uuid
    gradeId : uuid
}

class ProgramSubjectsSubject {
    programId : uuid
    subjectId : uuid
}

class Branding {
    id : uuid
    created_at : timestamp
    updated_at : timestamp
    primary_color : string
    organization_id : uuid
    status : Status
    deleted_at : timestamp
}

class BrandingImage {
    id : uuid
    created_at : timestamp
    updated_at : timestamp
    tag : string
    url : string
    branding_id : uuid
    status : Status
    deleted_at : timestamp
}

class AcademicTerm {
    id : uuid
    name : string
    start_date : timestamp
    end_date : timestamp
    school_id : uuid
    status : Status
    created_at : timestamp
    updated_at : timestamp
    deleted_at : timestamp
}

class Migrations {
    id : uuid
    name : string
    timestamp : timestamp
}

class OrganizationOwnership {
    organization_id : uuid
    user_id : uuid
    status : Status
    created_at : timestamp
    updated_at : timestamp
    deleted_at : timestamp
}

class PermissionRolesRole {
    permissionPermissionId : uuid
    roleRoleId : uuid
}

Role --* "0..1" Organization
User --* "0..1" Organization
AgeRange --* "0..1" Organization
Subcategory --* "0..1" Organization
Grade --* "0..1" Organization
Grade --* "0..1" Grade
Category --* "0..1" Organization
Category "1" *-- CategorySubcategoriesSubcategory
CategorySubcategoriesSubcategory --* "1" Subcategory
Subject --* "0..1" Organization
Subject "1" *-- SubjectCategoriesCategory
SubjectCategoriesCategory --* "1" Category
Program --* "0..1" Organization
Program "1" *-- ProgramAgeRangesAgeRange
ProgramAgeRangesAgeRange --* "1" AgeRange
Program "1" *-- ProgramGradesGrade
ProgramGradesGrade --* "1" Grade
Program "1" *-- ProgramSubjectsSubject
ProgramSubjectsSubject --* "1" Subject
User "1" *-- OrganizationMembership
OrganizationMembership --* "1" Organization
Class --* "0..1" Organization
Class "1" *-- SchoolClassesClass
SchoolClassesClass --* "1" School
Class "1" *-- ClassAgeRangesAgeRange
ClassAgeRangesAgeRange --* "1" AgeRange
Class "1" *-- ClassGradesGrade
ClassGradesGrade --* "1" Grade
Class "1" *-- ClassSubjectsSubject
ClassSubjectsSubject --* "1" Subject
Class "1" *-- ClassProgramsProgram
ClassProgramsProgram --* "1" Program
PermissionRolesRole --* "1" Role
PermissionRolesRole --* "1" Permission
School --* "0..1" Organization
School "1" *-- SchoolProgramsProgram
SchoolProgramsProgram --* "1" Program
User "1" *-- SchoolMembership
SchoolMembership --* "1" School
RoleMembershipsOrganizationMembership --* "1" Role
RoleMembershipsOrganizationMembership --* "1" OrganizationMembership
RoleSchoolMembershipsSchoolMembership --* "1" Role
RoleSchoolMembershipsSchoolMembership --* "1" SchoolMembership
UserClassesStudyingcClass --* "1" User
UserClassesStudyingcClass --* "1" Class
UserClassesTeachingClass --* "1" User
UserClassesTeachingClass --* "1" Class
Branding --* "1" Organization
BrandingImage --* "0..1" Branding
AcademicTerm --* "1" School
Class --* "0..1" AcademicTerm
OrganizationOwnership  --* "1" Organization
OrganizationOwnership  --* "1" User
@enduml

