@startuml
class User {
  user_id : uuid
  user_name : string
  given_name : string
  family_name: string
  email : string
  avatar : string
}

class UserProfile{
   user_profile_id : uuid
   user_profile_name : string
   user_profile_user : uuid
   myOrganizationOrganizationId : uuid
}

class Class {
  class_id : uuid
  class_name : string
  organizationOrganizationId : uuid
}

class Organization {
  organization_id : uuid
  organization_name : string
  address1 : string
  address2 : string
  phone : string
  shortCode : string
  primaryContactUserId : uuid
}

class OrganizationMembership {
  user_profile_id : string
  organization_id : string
  join_timestamp : timestamp
  userUserId : uuid
  organizationOrganizationId : uuid
}

class Permission {
  role_id : uuid
  permission_name : string
  allow : boolean
}

class Role {
  role_id : uuid
  role_name : string
  organizationOrganizationId : uuid
}

class School {
  school_id : uuid
  school_name : string
  organizationOrganizationId : uuid
}

class SchoolMembership {
  user_profile_id : string
  school_id : string
  join_timestamp : timestamp
  userUserId : uuid
  schoolSchoolId : uuid
}

class Attendance {
  user_id : string
  room_id : string
  session_id : string
  join_timestamp : timestamp
  leave_timestamp : timestamp
}

class RoleMembershipsOrganizationMembership {
  roleRoleId : uuid
  organizationMembershipUserProfileId : string
  organizationMembershipOrganizationId : string
}

class RoleSchoolMembershipsSchoolMembership {
  roleRoleId : uuid
  schoolMembershipUserProfileId : string
  schoolMembershipSchoolId : string
}

class UserClassesStudyingcClass {
  userUserProfileId : uuid
  classClassId : uuid
}

class UserClassesTeachingClass {
  userUserProfileId : uuid
  classClassId : uuid
}

class SchoolClassesClass {
  schoolSchoolId : uuid
  classClassId : uuid
}

Role -- "*" Organization
UserProfile -- "0..1" Organization
UserProfile "0..1" *-- "*" OrganizationMembership
UserProfile "*" -- "1" User
OrganizationMembership "*" --* "0..1" Organization
Class -- "0..1" Organization
Permission --* "0..1" Role
School -- "0..1" Organization
UserProfile "0..1" *-- "*" SchoolMembership
SchoolMembership "*" --* "0..1" School
RoleMembershipsOrganizationMembership "*" --* "1" Role
RoleMembershipsOrganizationMembership "*" --* "1" OrganizationMembership
RoleSchoolMembershipsSchoolMembership "*" --* "1" Role
RoleSchoolMembershipsSchoolMembership "*" --* "1" SchoolMembership
UserClassesStudyingcClass "*" --* "1" UserProfile
UserClassesStudyingcClass "*" --* "1" Class
UserClassesTeachingClass "*" --* "1" UserProfile
UserClassesTeachingClass "*" --* "1" Class
SchoolClassesClass "*" --* "1" School
SchoolClassesClass "*" --* "1" Class

@enduml

