export default {
    // Validation rules
    AGE_RANGE_LOW_VALUE_MIN: 0,
    AGE_RANGE_LOW_VALUE_MAX: 99,
    AGE_RANGE_HIGH_VALUE_MIN: 1,
    AGE_RANGE_HIGH_VALUE_MAX: 99,
    CLASS_NAME_MAX_LENGTH: 35,
    SCHOOL_NAME_MAX_LENGTH: 120,
    USER_GIVEN_NAME_MAX_LENGTH: 35,
    USER_FAMILY_NAME_MAX_LENGTH: 35
} as const
