export const validationConstants = {
    // Validation rules
    AGE_RANGE_LOW_VALUE_MIN: 0,
    AGE_RANGE_LOW_VALUE_MAX: 99,
    AGE_RANGE_HIGH_VALUE_MIN: 1,
    AGE_RANGE_HIGH_VALUE_MAX: 99,
    ORGANIZATION_NAME_MAX_LENGTH: 30,
    CLASS_NAME_MAX_LENGTH: 35,
    SCHOOL_NAME_MAX_LENGTH: 120,
    USER_GIVEN_NAME_MAX_LENGTH: 35,
    USER_FAMILY_NAME_MAX_LENGTH: 35,
    EMAIL_MAX_LENGTH: 250,
    ROLE_NAME_MAX_LENGTH: 20,
    SHORTCODE_MAX_LENGTH: 16,
    GENDER_MIN_LENGTH: 3,
    GENDER_MAX_LENGTH: 16,
    USERNAME_MAX_LEN: 35,
}

export default validationConstants
