{{- if .Values.istio.enabled }}
{{- if .Values.istio.createServiceEntries }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "user_service.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.userService.database.hostname }}
  trafficPolicy:
    tls:
      mode: SIMPLE
      credentialName: amazonaws-rds-ca-certs-{{ .Values.aws.region_name }}
      subjectAltNames:
        - {{ .Values.userService.database.hostname }}
      sni: {{ .Values.userService.database.hostname }}
{{- end }}
{{- end }}
