{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "user_service.labels" . | nindent 4 }}
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
