export const DefaultRoles = ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"]

export const DefaultPermissions = [
    { "name": "create_an_organization_account_1", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "delete_an_organization_account_2", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "reset_an_organization_account_3", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "setup_an_organizations_academic_profile_4", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "edit_an_organization_details_5", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "update_default_thumbnails_6", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "upgrade_organization_publishing_permissions_7", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "approve_and_reject_pending_content_8", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "create_program_category_9", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "change_an_organizations_visibility_settings_10", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "view_organization_bill_details_11", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "block_org_users_access__12", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "create_pricing_plan_13", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "logos_1000", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "my_account_1010", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "my_settings_1020", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "personalizations_1030", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "my_learners_page_1040", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "my_learners_dashboards_1041", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "my_learners_schedule_1042", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "my_learners_study_plan_1043", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "my_learners_notifications_1044", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "my_learners_make_a_payment_1045", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "my_learners_coupon_management_1046", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "my_learners_view_promotions_1047", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "my_learners_class_recordings_1048", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "my_learners_attendance_report_1049", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },

    { "name": "live_100", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "go_live_101", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },

    { "name": "view_organization_live_recordings_110", "roles": ["Organization Admin"] },
    { "name": "manage_live_classroom_recording_120", "roles": ["Organization Admin"] },
    { "name": "override_live_classroom_recording_130", "roles": ["Organization Admin"] },
    { "name": "delete_live_classroom_recordings_140", "roles": ["Organization Admin"] },
    { "name": "live_default_interface__170", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "auto_interface_based_on_age_range_171", "roles": ["Organization Admin", "Teacher"] },
    { "name": "record_live_classes_172", "roles": ["Organization Admin", "Teacher"] },
    { "name": "record_class_classes_173", "roles": ["Organization Admin", "Teacher"] },
    { "name": "collaboration_show_web_cam_dynamic_174", "roles": ["Organization Admin", "Teacher"] },
    { "name": "collaboration_show_web_cam_focus_175", "roles": ["Organization Admin", "Teacher"] },
    { "name": "collaboration_teacher_present_176", "roles": ["Organization Admin", "Teacher"] },
    { "name": "collaboration_observe_mode_177", "roles": ["Organization Admin", "Teacher"] },
    { "name": "collaboration_screenshare_mode_178", "roles": ["Organization Admin", "Teacher"] },
    { "name": "participants_tab_179", "roles": ["Organization Admin", "Teacher"] },
    { "name": "lesson_plan_tab_180", "roles": ["Organization Admin", "Teacher"] },
    { "name": "teaches_desk_tab_181", "roles": ["Organization Admin", "Teacher"] },
    { "name": "settings_tab_182", "roles": ["Organization Admin", "Teacher"] },
    { "name": "view_lesson_attachments_183", "roles": ["Organization Admin", "Teacher"] },
    { "name": "view_starred_content_184", "roles": ["Organization Admin", "Teacher"] },
    { "name": "see_recommended_content_based_on_age_range_185", "roles": ["Organization Admin", "Teacher"] },

    { "name": "attend_live_class_as_a_teacher_186", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "attend_live_class_as_a_student_187", "roles": ["Organization Admin", "Parent", "Student"] },

    { "name": "library_200", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "create_content_page_201", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "unpublished_content_page_202", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "pending_content_page_203", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "published_content_page_204", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "archived_content_page_205", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "view_asset_db_300", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "view_my_unpublished_content_210", "roles": ["Organization Admin", "Teacher", "School Admin"] },

    { "name": "view_org_unpublished_content_211", "roles": [] },

    { "name": "view_my_pending_212", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "view_org_pending__213", "roles": ["Organization Admin", "School Admin"] },
    { "name": "view_my_published_214", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "view_org_published__215", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },

    { "name": "view_my_archived_216", "roles": ["Organization Admin", "Teacher", "School Admin"] },

    { "name": "view_org_archived__217", "roles": ["Organization Admin", "School Admin"] },
    { "name": "view_my_school_published_218", "roles": ["School Admin"] },

    { "name": "create_lesson_material_220", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "create_lesson_plan_221", "roles": ["Organization Admin"] },
    { "name": "copy_content_222", "roles": ["Organization Admin", "School Admin"] },

    { "name": "create_my_schools_content_223", "roles": ["School Admin"] },
    { "name": "create_all_schools_content_224", "roles": ["Organization Admin"] },
    { "name": "view_my_school_pending_225", "roles": ["School Admin"] },
    { "name": "view_my_school_archived_226", "roles": ["School Admin"] },
    { "name": "view_all_schools_published_227", "roles": ["Organization Admin"] },
    { "name": "view_all_schools_pending_228", "roles": ["Organization Admin"] },
    { "name": "view_all_schools_archived_229", "roles": ["Organization Admin"] },
    
    { "name": "edit_my_unpublished_content_230", "roles": ["Organization Admin", "Teacher", "School Admin"] },

    { "name": "edit_org_unpublished_content_231", "roles": [] },

    { "name": "edit_my_pending_content_232", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "edit_org_pending_content_233", "roles": ["Organization Admin", "School Admin"] },
    { "name": "edit_my_published_content_234", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "edit_org_published_content_235", "roles": ["Organization Admin", "School Admin"] },
    { "name": "edit_lesson_material_metadata_and_content_236", "roles": ["Organization Admin"] },
    { "name": "edit_lesson_plan_metadata_237", "roles": ["Organization Admin"] },
    { "name": "edit_lesson_plan_content_238", "roles": ["Organization Admin"] },
    { "name": "download_lesson_plan_239", "roles": ["Organization Admin"] },

    { "name": "delete_my_unpublished_content_240", "roles": ["Organization Admin", "Teacher", "School Admin"] },

    { "name": "delete_my_schools_pending_241", "roles": ["Teacher"] },
    { "name": "remove_my_schools_published_242", "roles": ["Teacher"] },
    { "name": "delete_my_schools_archived_243", "roles": ["Teacher"] },

    { "name": "delete_all_schools_pending_244", "roles": ["Organization Admin"] },
    { "name": "remove_all_schools_published_245", "roles": ["Organization Admin"] },
    { "name": "delete_all_schools_archived_246", "roles": ["Organization Admin"] },

    { "name": "edit_my_schools_published_247", "roles": ["School Admin"] },
    { "name": "edit_my_schools_pending_248", "roles": ["School Admin"] },
    { "name": "edit_all_schools_published_249", "roles": ["Organization Admin"] },
    { "name": "edit_all_schools_pending_250", "roles": ["Organization Admin"] },

    { "name": "library_settings_270", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    
    { "name": "approve_pending_content_271", "roles": ["Organization Admin", "School Admin"] },
    { "name": "reject_pending_content_272", "roles": ["Organization Admin", "School Admin"] },
    { "name": "archive_published_content_273", "roles": ["Organization Admin", "School Admin"] },
    { "name": "republish_archived_content_274", "roles": ["Organization Admin", "School Admin"] },
    { "name": "delete_archived_content_275", "roles": ["Organization Admin", "School Admin"] },

    { "name": "details_upload_thumbnail_276", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "details_manually_add_program_277", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "details_manually_add_developmental_skill_278", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "details_manually_add_skills_category_279", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "details_manually_add_suitable_age_280", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "details_manually_add_grade_281", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "share_content_282", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "favorite_content_283", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "associate_learning_outcomes_284", "roles": ["Organization Admin", "Teacher", "School Admin"] },

    { "name": "publish_featured_content_with_lo_285", "roles": ["Organization Admin", "School Admin"] },
    { "name": "publish_featured_content_no_lo_286", "roles": ["Organization Admin", "School Admin"] },
    { "name": "publish_free_content_with_lo_287", "roles": ["Organization Admin", "School Admin"] },
    { "name": "publish_free_content_no_lo_288", "roles": ["Organization Admin", "School Admin"] },

    { "name": "asset_db_300", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "create_asset_page_301", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "view_asset_310", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "view_live_recordings_311", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "create_asset_320", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "upload_asset_321", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "edit_asset_330", "roles": ["Organization Admin", "School Admin"] },
    { "name": "download_asset_331", "roles": ["Organization Admin", "School Admin"] },
    { "name": "delete_asset_340", "roles": ["Organization Admin", "School Admin"] },
    { "name": "asset_db_settings_380", "roles": ["Organization Admin", "School Admin"] },

    { "name": "assessments_400", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "create_learning_outcome_page_401", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "unpublished_page_402", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "pending_page_403", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "learning_outcome_page_404", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "milestones_page_405", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "assessments_page_406", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "view_my_unpublished_learning_outcome_410", "roles": ["Organization Admin", "Teacher", "School Admin"] },

    { "name": "view_org_unpublished_learning_outcome_411", "roles": [] },

    { "name": "view_my_pending_learning_outcome_412", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "view_org_pending_learning_outcome_413", "roles": ["Organization Admin", "School Admin"] },
    { "name": "view_completed_assessments__414", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "view_in_progress_assessments_415", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "view_published_learning_outcome__416", "roles": ["Organization Admin", "Teacher", "School Admin"] },

    { "name": "view_unpublished_milestone_417", "roles": ["Organization Admin", "School Admin"] },
    { "name": "view_published_milestone_418", "roles": ["Organization Admin", "School Admin"] },
    { "name": "view_unpublished_standard_419", "roles": ["Organization Admin", "School Admin"] },
    { "name": "view_published_standard_420", "roles": ["Organization Admin", "School Admin"] },

    { "name": "create_learning_outcome__421", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "create_milestone_422", "roles": ["Organization Admin", "School Admin"] },
    { "name": "create_standard_423", "roles": ["Organization Admin", "School Admin"] },
    { "name": "edit_my_unpublished_learning_outcome_430", "roles": ["Organization Admin", "Teacher", "School Admin"] },

    { "name": "edit_org_unpublished_learning_outcome__431", "roles": [] },

    { "name": "remove_content_learning_outcomes_cart_432", "roles": ["Organization Admin"] },
    { "name": "add_content_learning_outcomes_433", "roles": ["Organization Admin"] },

    { "name": "edit_my_pending_learning_outcome_434", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "edit_org_pending_learning_outcome_435", "roles": ["Organization Admin", "School Admin"] },
    { "name": "edit_publsihed_learning_outcome_436", "roles": ["Organization Admin", "School Admin"] },
    { "name": "edit_attendance_for_completed_assessment_437", "roles": ["Organization Admin", "School Admin"] },
    { "name": "edit_attendance_for_in_progress_assessment_438", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "edit_in_progress_assessment_439", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "edit_unpublished_milestone_440", "roles": ["Organization Admin", "School Admin"] },
    { "name": "edit_published_milestone_441", "roles": ["Organization Admin", "School Admin"] },
    { "name": "edit_unpublished_standard_442", "roles": ["Organization Admin", "School Admin"] },
    { "name": "edit_published_standard_443", "roles": ["Organization Admin", "School Admin"] },
    { "name": "delete_my_unpublished_learninng_outcome_444", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "delete_org_unpublished_learning_outcome_445", "roles": ["Organization Admin", "School Admin"] },

    { "name": "delete_my_pending_learning_outcome_446", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "delete_org_pending_learning_outcome_447", "roles": ["Organization Admin", "School Admin"] },
    { "name": "delete_published_learning_outcome_448", "roles": ["Organization Admin", "School Admin"] },
    { "name": "delete_unpublishemilestone_449", "roles": ["Organization Admin", "School Admin"] },
    { "name": "delete_published_milestone_450", "roles": ["Organization Admin", "School Admin"] },
    { "name": "delete_unpublished_standard_451", "roles": ["Organization Admin", "School Admin"] },
    { "name": "delete_published_standard_452", "roles": ["Organization Admin", "School Admin"] },
    { "name": "assessment_settings_480", "roles": ["Organization Admin"] },
    { "name": "approve_pending_learning_outcome_481", "roles": ["Organization Admin"] },
    { "name": "reject_pending_learning_outcome_482", "roles": ["Organization Admin"] },
    { "name": "upload_learning_outcomes_483", "roles": ["Organization Admin"] },
    { "name": "download_learning_outcomes_484", "roles": ["Organization Admin"] },
    { "name": "add_learning_outcome_to_content_485", "roles": ["Organization Admin", "Teacher", "School Admin"] },

    { "name": "schedule_500", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "create_schedule_paage_501", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "view_my_calendar_510", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "view_org_calendar__511", "roles": ["Organization Admin", "School Admin"] },
    { "name": "view_school_calendar_512", "roles": ["Organization Admin", "School Admin"] },
    { "name": "create_event__520", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "edit_event__530", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "override_live_classroom_recording_setting_531", "roles": ["Organization Admin"] },
    { "name": "delete_event_540", "roles": ["Organization Admin", "Teacher", "School Admin"] },

    { "name": "schedule_settings_580", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "schedule_quick_start_581", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "schedule_search_582", "roles": ["Organization Admin", "School Admin"] },
    { "name": "reports_600", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "org_reports_601", "roles": ["Organization Admin"] },
    { "name": "school_reports_602", "roles": ["Organization Admin", "School Admin"] },
    { "name": "teacher_reports_603", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    
    { "name": "class_reports_604", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "student_reports_605", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },

    { "name": "view_reports_610", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "view_my_school_reports_611", "roles": ["School Admin"] },
    { "name": "view_my_organizations_reports_612", "roles": ["Organization Admin"] },
    { "name": "view_all_organizations_reports_613", "roles": [] },
    { "name": "view_my_reports_614", "roles": ["Teacher", "Parent", "Student"] },
    { "name": "share_report_630", "roles": ["Organization Admin", "School Admin"] },
    { "name": "download_report_631", "roles": ["Organization Admin", "School Admin"] },
    { "name": "report_settings_680", "roles": ["Organization Admin", "School Admin"] },

    { "name": "organizational_profile_10100", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "view_all_organization_details_page_10101", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "view_this_organization_profile_10110", "roles": ["Organization Admin", "School Admin"] },
    { "name": "view_my_organization_profile_10111", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "view_organization_details_10112", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "create_own_organization_10220", "roles": ["Parent", "Student"] },
    { "name": "edit_this_organization_10330", "roles": ["Organization Admin"] },

    { "name": "edit_my_organization_10331", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "edit_email_address_10332", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "edit_password_10333", "roles": ["Organization Admin", "Teacher", "School Admin"] },

    { "name": "delete_organization_10440", "roles": ["Organization Admin"] },
    { "name": "change_owner_10880", "roles": ["Organization Admin"] },
    { "name": "join_organization__10881", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },
    { "name": "leave_organization_10882", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },

    { "name": "school_resources_20100", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "define_school_program_page_20101", "roles": ["Organization Admin", "School Admin"] },
    { "name": "define_age_ranges_page_20102", "roles": ["Organization Admin", "School Admin"] },
    { "name": "define_grade_page_20103", "roles": ["Organization Admin", "School Admin"] },
    { "name": "view_school_20110", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "view_program_20111", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "view_age_range_20112", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "view_grades_20113", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "view_classes_20114", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "create_school_20220", "roles": ["Organization Admin", "School Admin"] },
    { "name": "create_program_20221", "roles": ["Organization Admin", "School Admin"] },
    { "name": "create_age_range_20222", "roles": ["Organization Admin", "School Admin"] },
    { "name": "create_grade_20223", "roles": ["Organization Admin", "School Admin"] },
    { "name": "create_class_20224", "roles": ["Organization Admin", "School Admin"] },
    { "name": "add_students_to_class_20225", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "add_teachers_to_class_20226", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "edit_school_20330", "roles": ["Organization Admin", "School Admin"] },
    { "name": "edit_program_20331", "roles": ["Organization Admin", "School Admin"] },
    { "name": "edit_age_range_20332", "roles": ["Organization Admin", "School Admin"] },
    { "name": "edit_grade_20333", "roles": ["Organization Admin", "School Admin"] },
    { "name": "edit_class_20334", "roles": ["Organization Admin", "Teacher", "School Admin"] },

    { "name": "move_students_to_another_class_20335", "roles": ["Organization Admin", "School Admin"] },

    { "name": "edit_teacher_in_class_20336", "roles": ["Organization Admin", "Teacher", "School Admin"] },

    { "name": "delete_school_20440", "roles": ["Organization Admin"] },
    { "name": "delete_program_20441", "roles": ["Organization Admin"] },
    { "name": "delete_age_range_20442", "roles": ["Organization Admin"] },
    { "name": "delete_grade_20443", "roles": ["Organization Admin"] },
    { "name": "delete_class_20444", "roles": ["Organization Admin"] },
    { "name": "delete_student_from_class_roster_20445", "roles": ["Organization Admin"] },
    { "name": "delete_teacher_from_class_20446", "roles": ["Organization Admin"] },
    { "name": "upload_schools__20880", "roles": ["Organization Admin"] },
    { "name": "download_schools_20881", "roles": ["Organization Admin"] },
    { "name": "upload_program_20882", "roles": ["Organization Admin"] },
    { "name": "download_program_20883", "roles": ["Organization Admin"] },

    { "name": "upload_class_roster_with_teachers_20884", "roles": ["Organization Admin", "School Admin"] },
    { "name": "download_class_roster_with_teachers_20885", "roles": ["Organization Admin"] },
    { "name": "upload_age_range_20886", "roles": ["Organization Admin"] },
    { "name": "download_age_range_20887", "roles": ["Organization Admin"] },
    { "name": "upload_grades_20888", "roles": ["Organization Admin"] },
    { "name": "download_grades_20889", "roles": ["Organization Admin"] },

    { "name": "upload_classes__20890", "roles": ["Organization Admin", "School Admin"] },

    { "name": "download_classes_20891", "roles": ["Organization Admin"] },
    { "name": "groups_30100", "roles": ["Organization Admin"] },
    { "name": "role_levels_30101", "roles": ["Organization Admin"] },
    { "name": "permissions_30102", "roles": ["Organization Admin"] },
    { "name": "view_groups_30110", "roles": ["Organization Admin"] },
    { "name": "view_role_priority_levels_30111", "roles": ["Organization Admin"] },
    { "name": "view_role_permissions_30112", "roles": ["Organization Admin"] },
    { "name": "create_groups_30220", "roles": ["Organization Admin"] },
    { "name": "create_role_priority_levels_30221", "roles": ["Organization Admin"] },
    { "name": "create_role_with_permissions_30222", "roles": ["Organization Admin"] },
    { "name": "edit_groups_30330", "roles": ["Organization Admin"] },
    { "name": "edit_role_priority_levels_30331", "roles": ["Organization Admin"] },
    { "name": "edit_role_permissions_30332", "roles": ["Organization Admin"] },
    { "name": "delete_groups_30440", "roles": ["Organization Admin"] },

    { "name": "users_40100", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "view_user_page_40101", "roles": ["Organization Admin"] },
    { "name": "view_users_40110", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "create_users_40220", "roles": ["Organization Admin", "School Admin"] },
    { "name": "edit_users__40330", "roles": ["Organization Admin", "School Admin"] },
    { "name": "delete_users_40440", "roles": ["Organization Admin", "School Admin"] },

    { "name": "upload_users_40880", "roles": ["Organization Admin"] },
    { "name": "download_users_40881", "roles": ["Organization Admin"] },
    { "name": "send_invitation_40882", "roles": ["Organization Admin", "School Admin"] },

    { "name": "deactivate_user_40883", "roles": ["Organization Admin"] },
    { "name": "billing_50100", "roles": ["Organization Admin"] },
    { "name": "view_payment_details_and_make_payment_50101", "roles": ["Organization Admin"] },
    { "name": "view_billing_details_50110", "roles": ["Organization Admin"] },
    { "name": "purchase_more_minutes_50880", "roles": ["Organization Admin"] },
    { "name": "purchase_more_storage_50881", "roles": ["Organization Admin"] },
    { "name": "purchase_next_plan_50882", "roles": ["Organization Admin"] },
    { "name": "download_billing_50883", "roles": ["Organization Admin"] },

    { "name": "support_60100", "roles": ["Organization Admin", "Teacher", "School Admin"] },
    { "name": "online_support_60101", "roles": ["Organization Admin", "Teacher", "School Admin", "Parent", "Student"] },

    { "name": "featured_programs_70000", "roles": ["Organization Admin"] },

    { "name": "view_any_featured_programs_70001", "roles": ["Organization Admin", "School Admin"] },
    { "name": "bada_rhyme_71000", "roles": ["Organization Admin", "School Admin"] },
    { "name": "bada_genius_71001", "roles": ["Organization Admin", "School Admin"] },
    { "name": "bada_talk_71002", "roles": ["Organization Admin", "School Admin"] },
    { "name": "bada_sound_71003", "roles": ["Organization Admin", "School Admin"] },
    { "name": "bada_read_71004", "roles": ["Organization Admin", "School Admin"] },
    { "name": "bada_math_71005", "roles": ["Organization Admin", "School Admin"] },
    { "name": "bada_stem_71006", "roles": ["Organization Admin", "School Admin"] },
    { "name": "badanamu_esl_71007", "roles": ["Organization Admin", "School Admin"] },

    { "name": "undefined_71008", "roles": [] },
    { "name": "undefined_71009", "roles": [] },
    { "name": "bada_rhyme_75000", "roles": [] },
    { "name": "bada_genius_75001", "roles": [] },
    { "name": "bada_talk_75002", "roles": [] },
    { "name": "bada_sound_75003", "roles": [] },
    { "name": "bada_read_75004", "roles": [] },
    { "name": "bada_math_75005", "roles": [] },
    { "name": "bada_stem_75006", "roles": [] },
    { "name": "badanamu_esl_75007", "roles": [] },
    { "name": "undefined_75008", "roles": [] },
    { "name": "undefined_75009", "roles": [] },
    { "name": "bada_rhyme_78000", "roles": [] },
    { "name": "bada_genius_78001", "roles": [] },
    { "name": "bada_talk_78002", "roles": [] },
    { "name": "bada_sound_78003", "roles": [] },
    { "name": "bada_read_78004", "roles": [] },
    { "name": "bada_math_78005", "roles": [] },
    { "name": "bada_stem_78006", "roles": [] },
    { "name": "badanamu_esl_78007", "roles": [] },
    { "name": "undefined_78008", "roles": [] },
    { "name": "unndefined_78009", "roles": [] },
    { "name": "publish_featured_content_for_all_hub_79000", "roles": [] },
    { "name": "publish_featured_content_for_specific_orgs_79001", "roles": [] },
    { "name": "publish_featured_content_for_all_orgs_79002", "roles": [] },

    { "name": "free_programs_80000", "roles": ["Organization Admin", "School Admin"] },
    { "name": "view_free_programs_80001", "roles": ["Organization Admin", "School Admin"] },
    { "name": "bada_rhyme_81000", "roles": ["Organization Admin", "School Admin"] },
    { "name": "bada_genius_81001", "roles": ["Organization Admin", "School Admin"] },
    { "name": "bada_talk_81002", "roles": ["Organization Admin", "School Admin"] },
    { "name": "bada_sound_81003", "roles": ["Organization Admin", "School Admin"] },
    { "name": "bada_read_81004", "roles": ["Organization Admin", "School Admin"] },
    { "name": "bada_math_81005", "roles": ["Organization Admin", "School Admin"] },
    { "name": "bada_stem_81006", "roles": ["Organization Admin", "School Admin"] },
    { "name": "badanamu_esl_81007", "roles": ["Organization Admin", "School Admin"] },

    { "name": "use_free_as_recommended_content_for_study_81008", "roles": [] },
    { "name": "undefinend_81009", "roles": [] },
    { "name": "bada_rhyme_85000", "roles": [] },
    { "name": "bada_genius_85001", "roles": [] },
    { "name": "bada_talk_85002", "roles": [] },
    { "name": "bada_sound_85003", "roles": [] },
    { "name": "bada_read_85004", "roles": [] },
    { "name": "bada_math_75005", "roles": [] },
    { "name": "bada_stem_75006", "roles": [] },
    { "name": "undefined_75007", "roles": [] },
    { "name": "undefined_75008", "roles": [] },
    { "name": "unndefined_75009", "roles": [] },
    { "name": "bada_rhyme_78000", "roles": [] },
    { "name": "bada_genius_78001", "roles": [] },
    { "name": "bada_talk_78002", "roles": [] },
    { "name": "bada_sound_78003", "roles": [] },
    { "name": "bada_read_78004", "roles": [] },
    { "name": "bada_math_78005", "roles": [] },
    { "name": "bada_stem_78006", "roles": [] },
    { "name": "badanamu_esl_78007", "roles": [] },
    { "name": "undefined_78008", "roles": [] },
    { "name": "unndefined_78009", "roles": [] },
    { "name": "publish_free_content_for_all_hub_79000", "roles": [] },
    { "name": "publish_free_content_for_specific_orgs_79001", "roles": [] },
    { "name": "publish_free_content_for_all_orgs_79002", "roles": [] }
]