import { PermissionName } from './permissionNames'

export const parentRole = {
    role_name: 'Parent',
    permissions: [
        PermissionName.live_100,
        PermissionName.go_live_101,
        PermissionName.attend_live_class_as_a_student_187,
        PermissionName.view_org_published_215,
        PermissionName.view_my_school_published_218,
        PermissionName.schedule_500,
        PermissionName.view_my_calendar_510,
        PermissionName.reports_600,
        PermissionName.student_reports_605,
        PermissionName.my_student_achievements_report_629,
        PermissionName.report_learning_summary_student_649,
        PermissionName.learning_summary_report_653,
        PermissionName.report_student_progress_student_661,
        PermissionName.student_progress_report_662,
        PermissionName.view_my_organization_profile_10111,
        PermissionName.create_own_organization_10220,
        PermissionName.join_organization_10881,
        PermissionName.leave_organization_10882,
        PermissionName.view_my_school_20119,
        PermissionName.view_program_20111,
        PermissionName.view_school_classes_20117,
        PermissionName.view_my_classes_20118,
        PermissionName.view_subjects_20115,
        PermissionName.view_my_admin_users_40114,
        PermissionName.create_my_users_40223,
        PermissionName.edit_my_users_40333,
        PermissionName.delete_my_users_40443,
        PermissionName.use_free_as_recommended_content_for_study_81008,
    ],
}
