import { PermissionName } from "../utils/permissionNames";

export const parentRole = {
    role_name: "Parent",
    permissions: [
        PermissionName.create_an_organization_account_1,
        PermissionName.delete_an_organization_account_2,
        PermissionName.reset_an_organization_account_3,
        PermissionName.setup_an_organizations_academic_profile_4,
        PermissionName.edit_an_organization_details_5,
        PermissionName.update_default_thumbnails_6,
        PermissionName.upgrade_organization_publishing_permissions_7,
        PermissionName.approve_and_reject_pending_content_8,
        PermissionName.create_program_category_9,
        PermissionName.change_an_organizations_visibility_settings_10,
        PermissionName.view_organization_bill_details_11,
        PermissionName.block_org_users_access__12,
        PermissionName.create_pricing_plan_13,
        PermissionName.logos_1000,
        PermissionName.my_account_1010,
        PermissionName.my_settings_1020,
        PermissionName.personalizations_1030,
        PermissionName.my_learners_page_1040,
        PermissionName.my_learners_dashboards_1041,
        PermissionName.my_learners_schedule_1042,
        PermissionName.my_learners_study_plan_1043,
        PermissionName.my_learners_notifications_1044,
        PermissionName.my_learners_make_a_payment_1045,
        PermissionName.my_learners_coupon_management_1046,
        PermissionName.my_learners_view_promotions_1047,
        PermissionName.my_learners_class_recordings_1048,
        PermissionName.my_learners_attendance_report_1049,
        PermissionName.live_100,
        PermissionName.go_live_101,
        PermissionName.attend_live_class_as_a_student_187,
        PermissionName.view_org_published__215,
        PermissionName.schedule_500,
        PermissionName.view_my_calendar_510,
        PermissionName.class_reports_604,
        PermissionName.student_reports_605,
        PermissionName.organizational_profile_10100,
        PermissionName.view_all_organization_details_page_10101,
        PermissionName.view_my_organization_profile_10111,
        PermissionName.view_organization_details_10112,
        PermissionName.create_own_organization_10220,
        PermissionName.join_organization__10881,
        PermissionName.leave_organization_10882,
        PermissionName.online_support_60101,
    ]
}