import { PermissionName } from "./permissionNames";

export const studentRole = {
    role_name: "Student",
    permissions: [
        PermissionName.logos_1000,
        PermissionName.my_account_1010,
        PermissionName.my_settings_1020,
        PermissionName.personalizations_1030,
        PermissionName.my_learners_page_1040,
        PermissionName.my_learners_dashboards_1041,
        PermissionName.my_learners_schedule_1042,
        PermissionName.my_learners_study_plan_1043,
        PermissionName.my_learners_notifications_1044,
        PermissionName.my_learners_make_a_payment_1045,
        PermissionName.my_learners_coupon_management_1046,
        PermissionName.my_learners_view_promotions_1047,
        PermissionName.my_learners_class_recordings_1048,
        PermissionName.my_learners_attendance_report_1049,
        PermissionName.live_100,
        PermissionName.go_live_101,
        PermissionName.attend_live_class_as_a_student_187,
        PermissionName.view_org_published_215,
        PermissionName.view_my_school_published_218,
        PermissionName.schedule_500,
        PermissionName.view_my_calendar_510,
        PermissionName.class_reports_604,
        PermissionName.student_reports_605,
        PermissionName.view_my_reports_614,
        PermissionName.organizational_profile_10100,
        PermissionName.view_all_organization_details_page_10101,
        PermissionName.view_my_organization_profile_10111,
        PermissionName.view_organization_details_10112,
        PermissionName.create_own_organization_10220,
        PermissionName.join_organization_10881,
        PermissionName.leave_organization_10882,
        PermissionName.online_support_60101,
        PermissionName.use_free_as_recommended_content_for_study_81008,
    ],
}
