name: Generate PlantUML Diagrams
on:
  push:
    paths:
      - "**.plantuml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg documents/*.plantuml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: "chore: svg files for plantuml diagrams"
          branch: ${{github.head_ref}}
